### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Crayon-new** [thu-ml/3D_Corruptions_AD#10]
https://github.com/thu-ml/3D_Corruptions_AD/blob/0cdf2c110ca079bdb10d4ef66b44c2a605f6792a/TransFusion/mmdet3d/datasets/pipelines/utils/fog_sim.py#L21
I have problem with that file, i can't find it in the repository.

**Comment by cuge1995** [comment]
Thank you for your attention. Regarding fog_sim, we recommend that you refer to https://github.com/MartinHahner/LiDAR_fog_sim to implement.
