### ISSUE TITLE
No such file or directory: 'xxx/utils/integral_lookup_tables/original'

### ISSUE THREAD

**Issue by Afreshbird** [thu-ml/3D_Corruptions_AD#12]
When I use the function of  'fog_sim' in 'LiDAR_corruptions.py', an error of 'No such file or directory: 'xxx/utils/integral_lookup_tables/original'' had occurred. 
I can't find the directory anywhere. 
Can anyone help me?

**Comment by cuge1995** [comment]
Thank you for your attention. Regarding fog_sim, we recommend that you refer to https://github.com/MartinHahner/LiDAR_fog_sim to implement.
