### ISSUE TITLE
utils和tools有点混乱

### ISSUE THREAD

**Issue by caimumuxin** [thu-ml/3D_Corruptions_AD#4]
LiDAR_corruptions.py中snow_sim_nus()函数有：
  from tools.snowfall.simulation import augment
  from tools.wet_ground.augmentation import ground_water_augmentation
  from tools.snowfall.sampling import snowfall_rate_to_rainfall_rate, compute_occupancy
是不是应该是from utils. ... 才对？类似的情况还出现在utils文件夹的多个文件中

**Comment by cuge1995** [comment]
As we wrote in the comments, we used https://github.com/SysCV/LiDAR_snow_sim, so there is nothing wrong with the `tools`.

**Comment by noob-dqt** [comment]
这个项目，压根就是不想让别人用，可能是不喜欢被人引用。。
