### ISSUE TITLE
Implement in mmdetection3d pipeline

### ISSUE THREAD

**Issue by qzhang852** [thu-ml/3D_Corruptions_AD#7]
Dear Author,
Thank you for your excellent work, I would if you try to implement the points corruption in the training pipeline of mmdetection3d? I have tried to add 
```python
    dict(
        type='CorruptionMethods',
        corruption_severity_dict=
            {
                'background_noise':1,
                # 'snow':2,
                # 'gaussian_noise_points':2,
            },
    ),
``` 
in the training pipeline, and got the error that 
```
pl = results['points'].tensor
KeyError: 'points'
```
Besides, if I want to use the `snow_sim_nus` function for nuscenes, do I have to convert `results['points']` to N * 6 firstly?
Thank you helping.

**Comment by cuge1995** [comment]
Thank you for your attention. First of all, we are evaluating the validation set, and have not tried it in training, but looking at your code, it should be that the point cloud in the training set has not been successfully read. Secondly, for snow_sim_nus, we strongly recommend you follow this repo (https://github.com/SysCV/LiDAR_snow_sim) to implement.
