### ISSUE TITLE
Request for Additional example on OpenPCDet Library and Paper Results

### ISSUE THREAD

**Issue by daixinguang** [thu-ml/3D_Corruptions_AD#8]
Hello,

Is great work!

I am currently using with the OpenPCDet Library and attempting to reproduce the results reported in your paper. However, I have encountered some difficulties and would greatly appreciate any additional information you can provide to aid in my efforts.

Firstly, I have noticed that some of the examples provided for supporting OpenPCDet are quite brief and the descriptions of certain functions are unclear. Therefore, such as:
1. `ImageBBoxMotionBlurFrontBack/ImageBBoxMotionBlurLeftRight` which function is you paper used. 
2. How to use `ImageBBoxOperation` for KITTI.

Secondly, in order to obtain $AP_{c,s}$, I need to run the `test.py` 27*5 times and manually calculate the average. While I am in the process of creating a script to automate this process, I would greatly appreciate any additional information you can provide to streamline this process.

Any additional information you can provide would be extremely helpful in my efforts to work with the OpenPCDet library and reproduce your results. I would also be happy to share my experience in reproducing this work.

Thank you in advance for your assistance.

**Comment by cuge1995** [comment]
Thank you for your attention, we have updated the relevant content in the OpenPCDet folder and README.
